### ISSUE TITLE
No mention of that "poetry add" writes to the lock file

### ISSUE THREAD

**Issue by thernstig** [sdispater/poetry#737] opened 2018-12-13 20:32 UTC
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Looking at https://raw.githubusercontent.com/sdispater/poetry/master/assets/install.gif I quickly noticed that `poetry add` updates the lock file. But there is no mention of this in the documentation at https://poetry.eustace.io/docs/cli/#add. At first I though I had to do `poetry add` and then `poetry lock`, but I am very glad that is not the case as your current behavior makes the most sense.

p.s. I am so glad I found poetry. You have all the sensible defaults and commands that I felt Pipenv was/is missing. Thank you!

**Comment by thernstig** [comment] 2018-12-13 20:42
I suppose the same could  be said about `poetry remove`. `poetry remove` also do not state anything that it will update `pyproject.toml` but I assume it will? (since `add` specifically does mention this).

**Comment by thernstig** [comment] 2019-11-13 18:30
Unstale

**Comment by sdispater** [comment] 2019-11-13 19:06
There is no need to mention it, in my opinion, since this is the expected behavior and the output of the commands clearly state with the `Writing lock file` line that it updates the lock file.

Closing.

**Closed by sdispater** 2019-11-13 19:06 UTC
