### ISSUE TITLE
Upload silently fails

### ISSUE THREAD

**Issue by sztomi** [sdispater/poetry#1261] opened 2019-07-28 13:27 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.04
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/sztomi/a82291b10982b4dc7b59af3b29b8ebd7

## Issue
I'm not able to publish anything to PyPI or TestPyPI. The upload appears to succeed, no error is shown, return code is 0; yet, nothing shows up on either repo. 

I've found the following similar issues:

  * https://github.com/sdispater/poetry/issues/858 - Tried `/simple`, `/legacy` for my testpypi repo conf, both silently failed; `/` fails with HTTP error 405.
  * https://github.com/sdispater/poetry/issues/742 - I have added a homepage entry and it didn't help

`poetry run twine upload ...` works without issues, so I believe this is a bug in poetry. I tried running with `-vvv` but no errors or suspisious output was shown.

**Comment by sdispater** [comment] 2019-08-02 15:11
Duplicate of #858. Closing.

**Closed by sdispater** 2019-08-02 15:11 UTC
Labels: Bug, CLI, Publishing

**Comment by sztomi** [comment] 2019-08-05 12:27
@sdispater I'm not convinced it is a duplicate: 

> poetry publish fails silently if the Pypi server returns an error

This is not the case here. PyPI happily accepts the upload (of the exact build that poetry produced) if it's done via twine.
