### ISSUE TITLE
Relax dependencies validation

### ISSUE THREAD

**Issue by tr11** [sdispater/poetry#1598] opened 2019-11-18 02:32 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
The following simple `pyproject.toml` file
```
[tool.poetry]
name = "poetry_test_1"
version = "0.1.0"
description = ""
authors=[]

[tool.poetry.dependencies]
python = "^3.7"
graphql-relay = {version = "3.0.0a1",allow-prereleases = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
gives an error when running a `poetry update`:
```
Updating dependencies
Resolving dependencies... (1.3s)

[RuntimeError]
The Poetry configuration is invalid:
  - Additional properties are not allowed ('licese' was unexpected)
  - [keywords] 'graphql relay api' is not of type 'array'
```

In this case, it seems there is a typo in the package `pyproject.toml` file that throws off the validation, which makes it impossible to use the listed dependency.  I was looking for a way to bypass the validation but I couldn't find anything directly that would do so.

If this is not possible with the current version, maybe we could add some option to skip the validation altogether on dependencies, or alternatively add a way to turn the validation `RuntimeError` into warnings instead.

**Comment by finswimmer** [comment] 2019-11-19 06:32
Hello,

this is a problem upstream and therefore out of scope of poetry. Please be so kind and inform the author of the package about the typo.

IMHO relaxing any validation isn't the way to go. That have the risk to have a system in an unreliable state.

I will close this issue for now. If you don't confirm with it, please leave a comment.

**Closed by finswimmer** 2019-11-19 06:32 UTC
Labels: Feature

**Comment by tr11** [comment] 2019-11-19 14:17
I understand your logic and agree that for publishing and building packages that should be the case, but I don't agree that this is outside the scope of poetry, especially when we think about a dev environment.

In my use case, I'm testing a new feature that requires the new alpha versions of a few packages.  I know it's unstable and it's not reliable, but that's kind of the intent of putting out an early alpha version so others can test.  The issue here is that poetry doesn't allow me to do so by default because someone has a typo in their setup file (which is good) nor it gives me an option to proceed at my own risk (I think this last one is desirable as long as we print out some warnings).

**Comment by finswimmer** [comment] 2019-11-19 20:09
Hello @tr11, 

> but I don't agree that this is outside the scope of poetry, especially when we think about a dev environment.

That's funny. Because I would argue the other way round :) Especially in dev environment one should be as much strict as possible about defined standards. That's the only way to catch up errors as early as possible.

It might happen that it take you hours to find out why something doesn't work. And in the end you you'll see that the cause is, not to take care about standards.

Furthermore the discussion would be endless to define in which aspects we can relax the validation and in which one we doesn't. The result would be a new standard:

![standard](https://imgs.xkcd.com/comics/standards.png)

So please report the issue to the package maintainer(s). I'm quite sure they will be very about feedback, the same as we are.

fin swimmer

**Comment by tr11** [comment] 2019-11-19 20:16
Let's not be pedantic here, I'm not proposing a new standard at all.  The feature request simply asks for a way to allow *temporary* errors so one can test unrelated features to the error.
