### ISSUE TITLE
Poetry 1.0.0b1 Fails to Install Wheel Files (`[TypeError] 'NoneType' object is not iterable'`)

### ISSUE THREAD

**Issue by KyleKing** [sdispater/poetry#1318] opened 2019-08-23 14:10 UTC
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 7 (will test on Mac tonight)
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A - toml file is irrelevant. Reproduce with `poetry new ...`. Script below

## Issue

Installing wheel files fails with the latest version of Poetry. I've tried multiple wheel files and seems to be a systemic bug.

This was probably related to the changes to remove `--git` and allowing the URL to be specified directly. I'll take a look tonight, but I'll be away this weekend and wanted to share a bug report

```sh
poetry add ./itsdangerous-1.1.0-py2.py3-none-any.whl -vvv
Using virtualenv: C:\Users\king.kyle\AppData\Local\pypoetry\Cache\virtualenvs\testnoniterablenonetype-NTCsUG5T-py3.7

[TypeError]
'NoneType' object is not iterable

Traceback (most recent call last):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\api\command\command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\api\command\command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\add.py", line 89, in handle
    packages, allow_prereleases=self.option('allow-prereleases')
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\init.py", line 280, in _determine_requirements
    requires = self._parse_requirements(requires)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\init.py", line 391, in _parse_requirements
    package = Provider.get_package_from_file(path.resolve())
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\puzzle\provider.py", line 255, in get_package_from_file
    for req in info["requires_dist"]:
```

## Steps to Reproduce

1. Summary

- Download the release files from `itsdangerous`: https://pypi.org/project/itsdangerous/1.1.0/#files
- Create new Poetry directory with `poetry new ...`
- Copy the wheel and tar.gz files into the new directory
- Try to install each file. The Wheel file fails, while the tar.gz file installs without issue

2. Simple Script

```sh
poetry --version
poetry new TestNonIterableNoneType
cd TestNonIterableNoneType
poetry install
poetry add ./itsdangerous-1.1.0.tar.gz -vvv
poetry remove itsdangerous
poetry add ./itsdangerous-1.1.0-py2.py3-none-any.whl -vvv
```

3. Script and Output

```sh
(py372) C:\Users\king.kyle\Developer\Pull Requests>poetry --version
Poetry version 1.0.0b1

(py372) C:\Users\king.kyle\Developer\Pull Requests>poetry new TestNonIterableNoneType
Created package TestNonIterableNoneType in TestNonIterableNoneType

(py372) C:\Users\king.kyle\Developer\Pull Requests>cd TestNonIterableNoneType

(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>dir
 Volume in drive C has no label.
 Volume Serial Number is E67C-A5F6

 Directory of C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType

23 Aug 19  09:49    <DIR>          .
23 Aug 19  09:49    <DIR>          ..
23 Aug 19  09:49               317 pyproject.toml
23 Aug 19  09:49                 0 README.rst
23 Aug 19  09:49    <DIR>          testnoniterablenonetype
23 Aug 19  09:49    <DIR>          tests
               2 File(s)            317 bytes
               4 Dir(s)  80,049,750,016 bytes free

(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>poetry install
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 10 installs, 0 updates, 0 removals

  - Installing zipp (0.5.2)
  - Installing importlib-metadata (0.19)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.1.0)
  - Installing colorama (0.4.1)
  - Installing more-itertools (7.2.0)
  - Installing pluggy (0.12.0)
  - Installing py (1.8.0)
  - Installing six (1.12.0)
  - Installing pytest (3.10.1)
  - Installing TestNonIterableNoneType (0.1.0)

(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>poetry add ./itsdangerous-1.1.0.tar.gz -vvv
Using virtualenv: C:\Users\king.kyle\AppData\Local\pypoetry\Cache\virtualenvs\testnoniterablenonetype-NTCsUG5T-py3.7

Updating dependencies
Resolving dependencies...
   1: fact: testnoniterablenonetype is 0.1.0
   1: derived: testnoniterablenonetype
   1: fact: testnoniterablenonetype depends on itsdangerous (*)
   1: fact: testnoniterablenonetype depends on pytest (^3.0)
   1: selecting testnoniterablenonetype (0.1.0)
   1: derived: pytest (^3.0)
   1: derived: itsdangerous (*)
   1: fact: pytest (3.10.1) depends on py (>=1.5.0)
   1: fact: pytest (3.10.1) depends on six (>=1.10.0)
   1: fact: pytest (3.10.1) depends on attrs (>=17.4.0)
   1: fact: pytest (3.10.1) depends on more-itertools (>=4.0.0)
   1: fact: pytest (3.10.1) depends on atomicwrites (>=1.0)
   1: fact: pytest (3.10.1) depends on pluggy (>=0.7)
   1: fact: pytest (3.10.1) depends on colorama (*)
   1: selecting pytest (3.10.1)
   1: derived: colorama (*)
   1: derived: pluggy (>=0.7)
   1: derived: atomicwrites (>=1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: six (>=1.10.0)
   1: derived: py (>=1.5.0)
   1: selecting itsdangerous (1.1.0 itsdangerous-1.1.0.tar.gz)
   1: selecting colorama (0.4.1)
   1: fact: pluggy (0.12.0) depends on importlib-metadata (>=0.12)
   1: selecting pluggy (0.12.0)
   1: derived: importlib-metadata (>=0.12)
   1: selecting atomicwrites (1.3.0)
   1: selecting more-itertools (7.2.0)
   1: selecting attrs (19.1.0)
   1: selecting six (1.12.0)
   1: selecting py (1.8.0)
PyPI: Invalid constraint (pathlib2 ; python_version == "3.4.*" or python_version < "3") found in importlib-metadata-0.19 dependencies, skipping
   1: fact: importlib-metadata (0.19) depends on zipp (>=0.5)
   1: selecting importlib-metadata (0.19)
   1: derived: zipp (>=0.5)
   1: selecting zipp (0.5.2)
   1: Version solving took 0.223 seconds.
   1: Tried 1 solutions.

Writing lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing itsdangerous (1.1.0 itsdangerous-1.1.0.tar.gz)


(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>poetry remove itsdangerous
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 0 installs, 0 updates, 1 removal

  - Removing itsdangerous (1.1.0 itsdangerous-1.1.0.tar.gz)

(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>poetry add ./itsdangerous-1.1.0-py2.py3-none-any.whl

[TypeError]
'NoneType' object is not iterable

(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>poetry add ./itsdangerous-1.1.0-py2.py3-none-any.whl -vvv
Using virtualenv: C:\Users\king.kyle\AppData\Local\pypoetry\Cache\virtualenvs\testnoniterablenonetype-NTCsUG5T-py3.7

[TypeError]
'NoneType' object is not iterable

Traceback (most recent call last):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\api\command\command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\clikit\api\command\command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\add.py", line 89, in handle
    packages, allow_prereleases=self.option('allow-prereleases')
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\init.py", line 280, in _determine_requirements
    requires = self._parse_requirements(requires)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\console\commands\init.py", line 391, in _parse_requirements
    package = Provider.get_package_from_file(path.resolve())
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py372\lib\site-packages\poetry\puzzle\provider.py", line 255, in get_package_from_file
    for req in info["requires_dist"]:


(py372) C:\Users\king.kyle\Developer\Pull Requests\TestNonIterableNoneType>
```

**Comment by abn** [comment] 2019-08-24 20:34
The root cause of this issue was that the wheel metadata did not contain any `Requires-Dist` entries, this scenario was not gracefully handled by the current code. This has been resolved in the above pull request.

**Closed** 2019-11-13 11:20 UTC
Labels: Bug, wontfix
