### ISSUE TITLE
Clarification on using poetry with non-package non-publish code

### ISSUE THREAD

**Issue by AEHamrick** [sdispater/poetry#1148] opened 2019-06-05 20:02 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
In a similar vein to #1050, I have a codebase of python and other files somewhat like:
```
[projectname]/
├── [library]/
│ ├── setup.py
│ ├── vendor_api.py
│ ├── utility.py
│ ├── custom_exceptions.py
├── [shell]/
│ ├── .bashrc
│ ├── .bash_profile
├── [sql]/
│ ├── load.sql
│ ├── dummy_data.sql
├── [config]/
│ ├── thing.cfg
|── readme.md
|── task.py
|── monitor.py
|── db_thing.py
└── task2.py
```

Currently I'm using `pipenv` for this, but I'd like to switch for a variety of reasons. Am I right thinking in this case I should `poetry init` in the top level of the project, put in a dummy version number, and forget the versioning and package/publish functionality exists? Are there any caveats that might bite me later?

**Comment by thejohnfreeman** [comment] 2019-06-12 21:28
See #1132 as well. I just set `version` to `0.0.0` and added `classifiers`:

```
classifiers = [
  "Private :: Do Not Upload",
]
```

There are no caveats.

**Comment by stephsamson** [comment] 2019-06-26 19:44
Thanks for submitting this issue!

Since this seems to be a duplicate of #1132 and there is already a longer trail of discussion there, I'll close this issue for now in an effort to consolidate and prune issues in `poetry`.

If you believe that this issue is different to #1132, please feel free to re-open this issue.

**Closed by stephsamson** 2019-06-26 19:44 UTC
Labels: Feature, Virtualenvs
