### ISSUE TITLE
Long paths are cut off in .tar.gz after running 'poetry build'

### ISSUE THREAD

**Issue by sgarcialaguna-mms** [sdispater/poetry#1018] opened 2019-04-05 08:55 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 1709
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/sgarcialaguna-mms/5a44ea984c7d8d5b35b32d34239bf288

## Issue
I have a long-ish, nested path name, let's say over a 100 characters. When I run poetry build, two files are created, a .tar.gz and a .whl. The .whl looks fine, but filenames in the .tar.gz are cut off. So instead of 'subfolder/subfolder/subfolder/module.py' the .tar.gz might include 'subfolder/subfolder/subfolder/modul'

**Comment by sgarcialaguna-mms** [comment] 2019-04-05 10:11
Okay, I looked into this further and this issue can probably be closed. I looked at the .tar.gz with 7-Zip and 7-Zip cannot parse TAR files with the PAX format (https://sourceforge.net/p/sevenzip/bugs/2116/). The file unpacks just fine with tar -xvzf

**Comment by hangtwenty** [comment] 2019-04-10 19:29
@sgarcialaguna-mms You can just close the the ticket yourself, no harm done because the closed tickets can always be found and/or referenced again. Closing helps everyone know the issue is not seeking further triage/investigation right now.

**Closed** 2019-04-11 07:06 UTC
