### ISSUE TITLE
.venv/bin/poetry lists system packages (and uses global pip)

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#392] opened 2018-08-14 13:04 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 18.04.1
- **Poetry version**: Poetry 0.11.4

## Issue

There are 3 ways to use poetry with virtualenv:
`poetry <cmd>` -- with global poetry
`.venv/bin/poetry <cmd>` -- with local poetry running directly
`. .venv/bin/activate` and then `poetry <cmd>` -- with local poetry running with virtualenv
Out of these three options, only `.venv/bin/poetry` works incorrectly.
Apparently, it uses the global system pip.

How to reproduce (note that I have global pip pointing to pip-3.6!):
```
sudo pip install scandir==1.6.0
virtualenv --python=python2.7 .venv
.venv/bin/pip install poetry
.venv/bin/poetry init . # how to skip the interactive prompt here?...
.venv/bin/poetry add -vvv scandir # will attempt to update scandir from 1.6.0 to 1.9.0, and will fail during that operation
```
I get:
```
$ .venv/bin/poetry update -vvv
Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on scandir (^1.9)
   1: selecting test (0.1.0)
   1: derived: scandir (^1.9)
PyPI: 1 packages found for scandir >=1.9,<2.0
   1: selecting scandir (1.9.0)
   1: Version solving took 0.006 seconds.
   1: Tried 1 solutions.


Package operations: 0 installs, 1 update, 0 removals

  - Updating scandir (1.6 -> 1.9.0)
                                                                                                       
[VenvCommandError]                                                                      
Command ['pip', 'install', '--no-deps', '-U', 'scandir==1.9.0'] errored with the following output:   
Collecting scandir==1.9.0                                                                            
Installing collected packages: scandir                                                               
  Found existing installation: scandir 1.6                                                           
    Uninstalling scandir-1.6:                                                                        
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/li  
b/python3.6/dist-packages/__pycache__/scandir.cpython-36.pyc'                                        
Consider using the `--user` option or check the permissions.
```

**Comment by sdispater** [comment] 2018-08-17 13:38
I think I know where the issue is coming from. Basically, it's the way that Poetry currently detects the virtualenv that causes it.

That's something I had in mind for a while but never had the time to tackle.

I will see what I can do for the next bugfix release.

**Comment by sdispater** [comment] 2018-10-18 23:28
This should be fixed the latest release.

**Closed by sdispater** 2018-10-18 23:28 UTC
Labels: bug

**Comment by buriy** [comment] 2018-10-19 09:37
Thanks a lot! This really helps in use-cases with Makefiles and reproducible setups, when I don't want to force people to install any packages globally (including poetry).
