### ISSUE TITLE
poetry install fails when a git repository with an ssh URL

### ISSUE THREAD

**Issue by thedrow** [sdispater/poetry#1255] opened 2019-07-26 08:40 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/thedrow/171e9e178499677f5838530e545c04fe

## Issue

I'm getting the following error when executing `poetry install`:

```
[EnvCommandError]                                                                                                                                                                            
Command ['/home/omer/.cache/pypoetry/virtualenvs/bootsteps-py3.7/bin/python', '-m', 'pip', 'install', '-e', '/home/omer/Documents/Projects/bootsteps'] errored with the following return code 1, and out        
put:                                                                                                                                                                                                      
Obtaining file:///home/omer/Documents/Projects/bootsteps                                                                                                                                                  
    ERROR: Command errored out with exit status 1:                                                                                                                                                        
     command: /home/omer/.cache/pypoetry/virtualenvs/bootsteps-py3.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/omer/Documents/Projects/bootsteps/setup.py'"'"'; __file__                 
='"'"'/home/omer/Documents/Projects/bootsteps/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_  
_, '"'"'exec'"'"'))' egg_info                                                                                                                                                                             
         cwd: /home/omer/Documents/Projects/bootsteps/                                                                                                                                                    
    Complete output (1 lines):                                                                                                                                                                            
    error in bootsteps setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid URL given                                   
    ----------------------------------------                                                                                                                                                              
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.     
```

There are no further details.

**Comment by sdispater** [comment] 2019-08-02 13:37
I can't reproduce with the example `pyproject.toml` you provided. Are you sure you are using the latest version of Poetry?

I am closing this. Feel free to reopen if you still experience the issue and, if so, please provide the full debug information by passing `-vvv` to the install command (as described in the issue template)

**Closed by sdispater** 2019-08-02 13:37 UTC

**Comment by smheidrich** [comment] 2020-08-26 04:12
@sdispater I have the same issue. It's only reproducible if you actually have a Python package folder (project_name/``__init__.py``) to go along with the ``pyproject.toml``, otherwise the installation won't complain. I put a boiled-down version of @thedrow's ``pyproject.toml`` [here](https://gist.github.com/smheidrich/f297067a50170a66d2793d81ef47258b). The only relevant line is

```
returns = { git = "git@github.com:dry-python/returns.git", branch = "master" }
```

Is that really the correct way to specify git dependencies accessible only via SSH, not HTTPS? Didn't find anything on that in the docs, and putting something starting with e.g. ``ssh://`` makes the subsequent ``git clone`` performed by poetry fail (cf. below). Would be good to have for dependencies between private repos, though.

Looking at the ``setup.py`` generated by ``poetry build``, the issue seems to be that this is what poetry put for ``install_requires``:

```
install_requires = \
['returns @ git+git@github.com:dry-python/returns.git@master']
```

So clearly it expected something starting with ``https://`` in which case the ``git+`` prefix would've made sense. So for this line to be correct, you would need to put ``ssh://`` in front of the line in ``pyproject.toml``, but, as I said above, then poetry's own ``git clone`` fails with:

```
[CalledProcessError]
Command '['git', 'clone', u'ssh://git@github.com:dry-python/returns.git', '/tmp/pypoetry-git-returnsHlmB70']' returned non-zero exit status 128
```

**Comment by finswimmer** [comment] 2020-08-26 04:52
Hello @smheidrich,

the dependency is described correct. But you have to make sure you have the necessary ssh-key(s) on your pc. This is what I get when trying to clone the repository:

```
$ git clone git@github.com:dry-python/returns.git
Cloning into 'returns'...
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

And that's the reason why a `poetry install` fails as well.

fin swimmer

**Comment by smheidrich** [comment] 2020-08-26 05:05
@finswimmer I do have that the ssh-key loaded into ssh-agent, that's not the issue.

**Comment by smheidrich** [comment] 2020-08-26 05:13
@finswimmer Can you reproduce this if you have your GitHub SSH keys loaded? Or does everything work fine in that case?
