### ISSUE TITLE
Poetry cannot be installed with Pip 18.1 (released 5 Oct)

### ISSUE THREAD

**Issue by azag0** [sdispater/poetry#485] opened 2018-10-09 20:36 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.14 
- **Poetry version**: 0.11.5 

## Issue

Poetry installation via `get-poetry.py` fails with Pip 18.1.

```
22:30 ~/Downloads python3 -m venv test
22:30 ~/Downloads test/bin/pip install --upgrade pip==18.0
Collecting pip==18.0
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
22:30 ~/Downloads curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | test/bin/python
Retrieving metadata

Installing version: 0.11.5
  - Getting dependencies
  - Vendorizing dependencies
  - Installing poetry

poetry (0.11.5) successfully installed!
22:30 ~/Downloads rm -rf test
22:31 ~/Downloads python3 -m venv test
22:31 ~/Downloads test/bin/pip install --upgrade pip==18.1
Collecting pip==18.1
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
22:31 ~/Downloads curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | test/bin/python
Retrieving metadata

Installing version: 0.11.5
  - Getting dependencies
  - Vendorizing dependencies
  - Installing poetry
An error has occured: Command '('/Users/hermann/Downloads/test/bin/python', '-m', 'pip', 'install', '--upgrade', '--no-deps', '/var/folders/hk/jzlc3y0x0svcny3v758kmvwr0000gn/T/poetry-installer-v1mvs_fr/poetry-0.11.5-py2.py3-none-any.whl')' returned non-zero exit status 2.
Processing /var/folders/hk/jzlc3y0x0svcny3v758kmvwr0000gn/T/poetry-installer-v1mvs_fr/poetry-0.11.5-py2.py3-none-any.whl
Installing collected packages: poetry
Exception:
Traceback (most recent call last):
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/Users/hermann/Downloads/test/lib/python3.7/site-packages/pip/_internal/wheel.py", line 514, in move_wheel_files
    for row in sorted(outrows):
TypeError: '<' not supported between instances of 'int' and 'str'

22:32 ~/Downloads [2] 
```

**Comment by jtbeach** [comment] 2018-10-10 04:55
Bug in pip -- see https://github.com/pypa/pip/issues/5868

**Comment by y4n9squared** [comment] 2018-10-16 00:39
There has been a discussion in pypa/pip#5868 regarding this issue, and based on https://github.com/pypa/pip/issues/5868#issuecomment-430060402, it seems like the bug is in Poetry. If the maintainers agree that this is the root cause, it's an easy fix.

**Comment by sdispater** [comment] 2018-10-16 16:14
Actually this is not an issue in how Poetry builds wheels, so there is nothing to be done in the code.

It actually is an issue in the current installer (`get-poetry.py`). This has already been fixed on the `develop` branch by the implementation of a new installer (see #378) and the next `0.12.0` release will make this new installer available.

So, as far as I know, this is not an issue on `pip`'s end.

**Comment by y4n9squared** [comment] 2018-10-16 17:12
@sdispater thanks for the update! I think there is currently some discussion whether or not this "issue" is really an issue or just needs to be handled properly for all RECORD files. #378 will resolve this issue for Poetry though.

https://github.com/pypa/pip/issues/5868#issuecomment-430282534

**Comment by sdispater** [comment] 2018-11-12 18:46
This has been fixed now that the `get-poetry.py` installer has been updated.

**Closed by sdispater** 2018-11-12 18:46 UTC
