### ISSUE TITLE
Poetry creates a setup.py when installing dependencies specified by path

### ISSUE THREAD

**Issue by cauebs** [sdispater/poetry#211] opened 2018-06-13 18:50 UTC
As the title says, the setup.py is created and left in the other package's directory, which might not be expected by the user. This only happens if the dependency uses poetry and doesn't initially contain a setup.py file.

https://github.com/sdispater/poetry/blob/master/poetry/packages/directory_dependency.py#L74

Is this the intended behaviour or should the file be removed afterwards?

**Comment by sdispater** [comment] 2018-06-15 16:06
It is not necessary when getting the dependency information, since we can retrieve everything from the `pyproject.toml` file. However, for now, we need the `setup.py` file when installing the package (this is something that will likely changed in the future).

However, I wonder if we can defer the `setup.py` creation and only do it at the installation step.

**Comment by dfee** [comment] 2018-08-08 22:36
Creating the `setup.py` isn't as troubling as leaving it around. I have the following structure:

```
myrepo/
    mypkg.core/
        pyproject.toml
    mypkg.asdf/
        pyproject.toml
```

Unsurprisingly, `mypkg.asdf` has a requirement on `mypkg.core`. The problem is when they're simultaneously "developed" and a `tool.poetry.plugins` (for example) changes and I need to re-"poetry develop" the changed module.

For example, imagine that I add another `tool.poetry.plugins.console_scripts` entry to `mypkg.core`'s `pyproject.toml`. There's an artifact `setup.py` lying around due to it's previous installation (with `--develop`) in the `mpkg.asdf` package.

The solution is deleting the outdated `setup.py` and then running `poetry develop` for `mypkg.core` again, (which auto deletes the `setup.py` file). Then, running `poetry install` again in `mypkg.asdf`. Of course, a new artifact `setup.py` is created again.

**solution**
Delete the `setup.py` after you've used it... or use `tempfile`.

**Comment by sdispater** [comment] 2018-11-12 01:40
This should now be fixed in the latest releases.

**Closed by sdispater** 2018-11-12 01:40 UTC
Labels: Installation, enhancement
