### ISSUE TITLE
'poetry develop' constantly reinstalls setuptools

### ISSUE THREAD

**Issue by jacebrowning** [sdispater/poetry#196] opened 2018-06-08 12:53 UTC
I expected to see "0 installs, 0 updates, 0 removals" after `$ poetry develop` runs the first time.

```
$ poetry --version
Poetry 0.10.3

$ poetry new foobar
Created package foobar in foobar

$ cd foobar

$ poetry develop
Creating virtualenv foobar-py3.6 in /private/tmp/foobar/.venv
Updating dependencies
Resolving dependencies... (0.3s)


Package operations: 8 installs, 0 updates, 0 removals

Writing lock file

  - Installing atomicwrites (1.1.5)
  - Installing attrs (18.1.0)
  - Installing more-itertools (4.2.0)
  - Installing pluggy (0.6.0)
  - Installing py (1.5.3)
  - Installing setuptools (39.2.0)
  - Installing six (1.11.0)
  - Installing pytest (3.6.1)
Installing foobar (0.1.0)

$ poetry develop
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing setuptools (39.2.0)
Installing foobar (0.1.0)

$ poetry develop
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing setuptools (39.2.0)
Installing foobar (0.1.0)

$ poetry lock
Updating dependencies
Resolving dependencies... (0.1s)


Writing lock file


$ poetry develop
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing setuptools (39.2.0)
Installing foobar (0.1.0)

$ poetry develop
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing setuptools (39.2.0)
Installing foobar (0.1.0)
```

**Comment by sdispater** [comment] 2018-06-08 16:31
Yes, I noticed that too. It's caused by a recent changed in the resolver. Before this change, `setuptools` would not be selected by the resolver since it was considered unsafe. Now, however, it is picked up by the resolver and is locked inside the lock file.

However, when the resolver checks if it is currently installed (by using `pip freeze` internally) it does not see it since packages like `pip` or `setuptools` do not appear by default, you actually have to use `pip freeze --all` to see them.

But now that I think about it, this can lead to some undesired effects, since if a package sets `pip` as a dependency and is uninstalled later, `pip` will also be uninstalled which will cause broken virtualenv.

I think I will reintroduce the notion of "unsafe" packages to avoid this.

**Comment by sdispater** [comment] 2018-07-26 22:16
This should be fixed now.

**Closed by sdispater** 2018-07-26 22:16 UTC
