### ISSUE TITLE
poetry applies constraint from extras_require even if not used

### ISSUE THREAD

**Issue by stefanfoulis** [sdispater/poetry#551] opened 2018-10-23 22:25 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: debian (`python:3.6-stretch` docker image)
- **Poetry version**: `0.12.4`

## Issue
`poetry` seems to be using a version constraint from an `extras_require` which it should not.

```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["None"]

[tool.poetry.dependencies]
python = "3.6"
hyper = "^0.7.0"
cryptography = "^2.3"

[tool.poetry.dev-dependencies]
```

```bash
# poetry lock
Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
Because hyper (0.7.0) depends on cryptography (<1.0)
 and no versions of hyper match >0.7.0,<0.8.0, hyper (>=0.7.0,<0.8.0) requires cryptography (<1.0).
So, because app depends on both hyper (^0.7.0) and cryptography (^2.3), version solving failed.

lock
```

`hyper` does have a `extras_require` entry in `setup.py` that limits to `cryptography<1.0`, but I don't think that constraint should be applied in this case.

```python
    extras_require={   
        # PyPy with bad SSL modules will likely also need the cryptography
        # module at lower than 1.0, because it doesn't support CFFI v1.0 yet.
        ':platform_python_implementation == "PyPy" and python_full_version < "2.7.9"': [
            'cryptography<1.0'
        ]
    }
```

See https://github.com/Lukasa/hyper/blob/v0.7.0/setup.py#L97-L99

**Comment by sdispater** [comment] 2018-10-24 17:23
Sorry about that!

This is fixed in commit 5acb920.

The error was caused by the fact that the dependency resolver was not using the `python_full_version` marker and thus was picking up `cryptography<1.0` as a necessary dependency which was not the case for your project since you specified `python = "3.6"`.

The fix will land in the next bugfix release which should be out this week.

**Comment by stefanfoulis** [comment] 2018-10-24 18:41
Awesome! Thanks @sdispater 🎩

**Comment by stefanfoulis** [comment] 2018-10-24 20:35
I tested with https://github.com/sdispater/poetry/commit/5acb920d083641038a6bb6015b1665984d1718b7 and can confirm it works for me now.

**Comment by sdispater** [comment] 2018-10-26 18:00
Release `0.12.5` is out!

**Closed by sdispater** 2018-10-26 18:00 UTC
Labels: Dependency resolution, bug
