### ISSUE TITLE
Error when adding package: EmptyConstraint instance has no attribute 'min'

### ISSUE THREAD

**Issue by bi1yeu** [sdispater/poetry#534] opened 2018-10-19 16:11 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.6
- **Poetry version**: 0.12.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/bi1yeu/41b2180afd838560daa0faf68e9c236b

## Issue

Hi! This is my first time attempting to use poetry. I created a new empty project with this command:

```
$ poetry new example
```

Then, from within the `example` directory, I attempt to add the [`jupyter`](https://pypi.org/project/jupyter/) package:

```
$ poetry add jupyter
Using version ^1.0 for jupyter

Updating dependencies
Resolving dependencies... (4.0s)

[AttributeError]
EmptyConstraint instance has no attribute 'min'

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

Verbose output is contained within the gist linked above. I am able to add other packages without apparent error. Happy to provide additional info.

**Comment by sdispater** [comment] 2018-10-19 22:00
There was an issue when parsing some transitive markers. It has been fixed in commit 7761867

**Comment by sdispater** [comment] 2018-10-22 23:08
This has been fixed in the latest release.

**Closed by sdispater** 2018-10-22 23:08 UTC
Labels: bug

**Comment by flaviut** [comment] 2019-07-11 14:50
I think there's been a regression here; I get the same error with 0.12.16:

```console
$ poetry -V
Poetry 0.12.16
$ poetry add jupyter
                                                   
[AttributeError]                    
'EmptyConstraint' object has no attribute 'min'  
                                                   
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**Comment by mwoyuan** [comment] 2019-08-10 15:59
Got the same error with 0.12.17 & Python version 3.7.4; same prompt.

It seems to be `create_nested_marker()` missing `EmptyConstraint` when checking the type of `constraint`. Manual patching `~/.poetry/lib/poetry/packages/utils/utils.py` to import `poetry.semver.empty_constraint.EmptyConstraint` and add it to check list said above solved the problem locally.

**Comment by agilgur5** [comment] 2019-09-10 04:14
Also getting this error with Poetry `0.12.17`. Can we re-open this issue?

@mwoyuan to which check (line #?) did you add `EmptyConstraint`? Maybe submit a PR if you were able to patch it?

**Comment by laike9m** [comment] 2020-02-03 00:24
Met this issue on Poetry 1.0.3

**Comment by andreoliwa** [comment] 2020-06-23 23:55
I'm having the same error on Poetry 1.0.9.

The package I'm trying ([AuHau/toggl-cli](https://github.com/AuHau/toggl-cli/blob/master/setup.cfg#L10)) has:

```
python_requires = >=3.6.0, <3.9.0
```

This is my debug info, and a gist below with `pyproject.toml` and the full error log.
```
Poetry
Version: 1.0.9
Python:  3.8.3

Virtualenv
Python:         3.8.3
Implementation: CPython
Path:           /Users/wagneraugusto/Library/Caches/pypoetry/virtualenvs/toggl-cli-bug-t9z0mPRw-py3.8
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/wagneraugusto/.pyenv/versions/3.8.3
```

[Poetry [AttributeError] 'EmptyConstraint' object has no attribute 'min'](https://gist.github.com/andreoliwa/252642640bd51ba958ddd01dcdde2de8)

**Comment by glencairn** [comment] 2021-03-03 21:09
I'm experiencing this same issue with _Poetry 1.1.4_ when trying to install certain packages. I was able to get around the issue following a similar approach that @bnoctis and @agilgur5 detailed above. However, for a more recent vendorized install, the file I had to modify was `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/packages/dependency.py` (where python3.8 is my active interpreter).

Here's a diff of the modifications I made, hopefully others find this useful:

```diff
diff --git a/tmp.py b/Users/user/.poetry/lib/poetry/_vendor/py3.8/poetry/core/packages/dependency.py
index e118794..6f97002 100644
--- a/tmp.py
+++ b/Users/user/.poetry/lib/poetry/_vendor/py3.8/poetry/core/packages/dependency.py
@@ -9,6 +9,7 @@ from poetry.core.semver import Version
 from poetry.core.semver import VersionConstraint
 from poetry.core.semver import VersionRange
 from poetry.core.semver import VersionUnion
+from poetry.core.semver import EmptyConstraint
 from poetry.core.semver import parse_constraint
 from poetry.core.version.markers import AnyMarker
 from poetry.core.version.markers import parse_marker
@@ -291,6 +292,8 @@ class Dependency(PackageSpecification):
                 name = "python_full_version"
 
             marker = '{} == "{}"'.format(name, constraint.text)
+        elif isinstance(constraint, EmptyConstraint):
+            marker = ''
         else:
             if constraint.min is not None:
                 min_name = name
```

---

System: MacOS 
Poetry: 1.1.4

**Comment by leikoilja** [comment] 2021-03-13 08:11
Flip, tool me good 30 mins to fix it.
MacOS M1, Poetry 1.1.5.
Had to do both those fixes as mentioned above by @glencairn and @bnocti, @agilgur5

**Comment by Ver1Sus** [comment] 2021-03-26 08:11
Like @glencairn comment, but this works for me:
```python
        elif constraint.is_empty():
            marker = ''
```
System: Ubuntu 20
Poetry: 1.0.1
Python: 2.7

P.S. Iam not sure, but this package was causing an error `backports.functools-lru-cache (1.6.3)`

**Comment by pksol** [comment] 2021-03-31 09:32
Thanks, @Ver1Sus!
backports.functools-lru-cache was causing problems for me as well and fixating its version to 1.6.1 fixed it.

Tell me, how did you know that the problem was with this particular package? I'm wondering since it might happen again with another package.

**Comment by gjedlicska** [comment] 2021-04-01 20:31
Same issue here, my poetry debug is 

```
Poetry
Version: 1.1.5
Python:  3.8.8

Virtualenv
Python:         3.8.8
Implementation: CPython
Path:           /home/gergojedlicska/.cache/pypoetry/virtualenvs/prjectproject-kXrNwMJU-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /home/gergojedlicska/.asdf/installs/python/3.8.8
```

**Comment by willfrey** [comment] 2021-04-02 05:45
This is also happening due to a change in [pytest-randomly](https://github.com/pytest-dev/pytest-randomly/blob/main/setup.cfg#L35), FWIW.

**Comment by Ver1Sus** [comment] 2021-04-02 10:41
@pksol, I'm glad that the solution helped!

I ran `poetry update -vvv` with verbose, and poetry pointed out the problematic package:

```bash
PyPI: 8 packages found for backports.functools-lru-cache >=1.2.1
 1 packages found for backports.functools-lru-cache >=1.2.1
   1: Version solving took 40.500 seconds.
   1: Tried 1 solutions.

[AttributeError]
EmptyConstraint instance has no attribute 'min'
```

**Comment by dem1tris** [comment] 2021-04-02 13:16
For me it fails checking `lazy-object-proxy` version, I guess
```
$ poetry --version
Poetry version 1.1.5

$ poetry update -vvv
...
PyPI: 8 packages found for lazy-object-proxy >=1.4.0
   2: selecting lazy-object-proxy (1.6.0)
   2: Version solving took 2.466 seconds.
   2: Tried 2 solutions.

  Stack trace:
...
```

**Comment by jamie--stewart** [comment] 2021-04-05 14:12
I'm seeing the same issue as @glencairn identified:

* `macOs 11.0.1`
* `poetry 1.1.15`
* `python 3.8.7`

The patch they identified has fixed my issue. 

Can anyone guide me on how to identify the offending package? I think we may need to raise a fresh issue here as it seems like whatever causes this has not been resolved, or resurfaced

**Comment by gatoniel** [comment] 2021-04-06 08:35
I encountered the same issue and the solution of @glencairn solved the problem. My `poetry debug` is:

```
Poetry
Version: 1.1.5
Python:  3.8.8

Virtualenv
Python:         3.8.8
Implementation: CPython
Path:           /home/netter/.cache/pypoetry/virtualenvs/stereographic-link-prediction-ra14Y8Aq-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /home/netter/miniconda3
```

**Comment by dycw** [comment] 2021-04-07 06:06
I found @dem1tris's solution to be helpful - I changed `pytest-randomly = "^3.5"` to `"3.5.0"`.

**Comment by tony** [comment] 2021-04-11 15:40
> backports.functools-lru-cache was causing problems for me as well and fixating its version to 1.6.1 fixed it.

`poetry update` running this does it.   Poetry 1.0.10

`pyflakes` gave me this via `flake8`

**Comment by tony** [comment] 2021-04-11 15:49
Follow up

If your issue in [`backbords.functools-lru-cache`](https://github.com/jaraco/backports.functools_lru_cache/):

Workaround: @pbzweihander's fix [here](https://github.com/spoqa/requests-backoff/commit/2436d62d3a6527cd51a3fdc2b84b9a18c105288c) helped me in pyproject.toml:

```toml
"backports.functools_lru_cache" = "!=1.6.2,!=1.6.3" # https://github.com/jaraco/backports.functools_lru_cache/pull/16
```

There is a PR to fix this here: https://github.com/jaraco/backports.functools_lru_cache/pull/16

**Comment by mforbes** [comment] 2021-05-07 00:01
I still have an issue with Poetry version 1.1.6.

```toml
# pyproject.toml
[tool.poetry]
name = "temp"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^2.7,^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```bash
$ poetry add pip

  AttributeError

  'EmptyConstraint' object has no attribute 'min'

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/packages/utils/utils.py:249 in create_nested_marker
      245│         marker = glue.join(parts)
      246│     elif isinstance(constraint, Version):
      247│         marker = '{} == "{}"'.format(name, constraint.text)
      248│     else:
    → 249│         if constraint.min is not None:
      250│             op = ">="
      251│             if not constraint.include_min:
      252│                 op = ">"
      253│ 
```

**Comment by elicutler** [comment] 2021-08-19 13:32
I had to edit `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/version/markers.py` 
```
from poetry.core.packages.constraints.empty_constraint import EmptyConstraint
```
and line 281 in the definition of `validate(self, environment)`, added:
```
if isinstance(self._constraint, EmptyConstraint):
    return True

```

**Comment by mdengler** [comment] 2021-08-19 17:23
> I had to edit `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/version/markers.py`
> [...]

I opened an issue for this specific error: https://github.com/python-poetry/poetry/issues/4410

**Comment by Mazyod** [comment] 2021-08-24 07:12
> I had to edit `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/version/markers.py`
> 
> ```
> from poetry.core.packages.constraints.empty_constraint import EmptyConstraint
> ```
> 
> and line 281 in the definition of `validate(self, environment)`, added:
> 
> ```
> if isinstance(self._constraint, EmptyConstraint):
>     return True
> ```

Just to avoid the import in my case, I used `not hasattr(self._constraint, "allows")`

**Comment by dsmore** [comment] 2021-08-24 17:48
Experienced this issue with poetry version 1.1.7.
In my experience, I can confirm upgrading to poetry version 1.1.8 resolves this issue.

**Comment by dsm0014** [comment] 2021-08-24 17:51
Encountered this issue with poetry version 1.1.7.
In my experience, I can confirm updating to version 1.1.8 resolves this issue.

**Comment by errsolve7** [comment] 2021-09-09 04:28
[[Already Solved] AttributeError ‘EmptyConstraint’ object has no attribute ‘allows’](https://exerror.com/attributeerror-emptyconstraint-object-has-no-attribute-allows/)

**Comment by iXanthos** [comment] 2021-12-12 13:28
This issue still persists at poetry 1.1.12. When running `poetry add --dev pytest pytest-cov black isort flake8 bandit safety`
