### ISSUE TITLE
Poetry install no longer removes dev dependencies

### ISSUE THREAD

**Issue by bertjwregeer** [sdispater/poetry#513] opened 2018-10-18 06:32 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS
- **Poetry version**: 0.12.2

## Issue
\
There is currently no way to go from a `develop` `poetry install` to one that has `--no-dev`.

In previous versions, if you ran `poetry install --no-dev` it would remove all dev dependencies from the current virtual environment.

**Comment by sdispater** [comment] 2018-10-18 15:04
Yes, I can definitely reproduce.

Was it working in `0.11.5`? If yes, it's definitely a change made in the resolver that's causing this issue.

**Comment by bertjwregeer** [comment] 2018-10-18 16:10
This was working on the 0.11 series at one point, I remember using it.

**Comment by sdispater** [comment] 2018-10-18 18:55
Commit 76801fd should fix the issue. I will try to make a bugfix release as soon as possible.

**Comment by sdispater** [comment] 2018-10-19 22:10
This is fixed in the latest release.

**Closed by sdispater** 2018-10-19 22:10 UTC
Labels: Dependency resolution, Installation, bug

**Comment by goosemo** [comment] 2019-04-29 19:05
This behavior seems like a bug, especially in how `--no-dev` is documented. 

> --no-dev: Do not install dev dependencies

This doesn't state that `poetry` will uninstall anything. Can this be addressed with docs and perhaps a flag or configuration to not have this behavior happen?

My use case for example is to not have `poetry` uninstall every python package I have installed inside a docker container, or a developer machine, when it is configured to not use virtualenvs.

**Comment by prokher** [comment] 2019-05-12 10:08
@goosemo As for me it is looks like a bug as well. Consider the following use-case.

In the `Dockerfile` I install 2 Python packages. The first one requires a package `A`, while the second one has this package `A` in it in the `[tool.poetry.dev-dependencies]` section. As a result, the second `poetry install` invocation removes the package `A` from the container and the first package breaks.

Probably `poetry install` indeed shall behave like this by default (e.g. for the backward compatibility), but there must be a command line argument to not remove anything already installed.

@sdispater I am not sure if this is OK to comment on the closed issues in your repository, please tell if it is necessary to create a new one.

**Comment by laike9m** [comment] 2020-07-24 05:49
+1 on previous comments. Having no way to turn off the behavior of removing dev packages is not ideal, and I believe I have a legit use case to prove it.

I'm using Poetry for dependency management and tox for testing.

The depdencies I have are like this:

```toml
[tool.poetry.dependencies]
python = "^3.7.0"
pygments = "^2.6.1"
crayons = "^0.3.0"
deepdiff = "^5.0.0"
grpcio = "^1.30.0"
protobuf = "^3.12.2"
shortuuid = "^1.0.1"
attrs = "^19.3.0"
get-port = "^0.0.5"
jsonpickle = "^1.4.1"
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
tox = "^3.14"
tox-pyenv = "^1.1"
pytest-xdist = "^1.31"
pytest = "^5.4.3"
pyhamcrest = "^2.0.2"
dephell = "^0.8.3"
bytecode = "^0.11.0"
grpcio-tools = "^1.30.0"
```

Not **every** dev dependency is needed in tests, for example `grpcio-tools`, is not needed. So here's my `tox.ini` file:

```int
[tox]
isolated_build = true
envlist = py37,py38

[testenv]
commands =
    pip install poetry
    poetry config virtualenvs.create false
    poetry install --no-dev
    pip install pytest pytest-xdist pyhamcrest

    py.test -s -vv {posargs} {toxinidir}/test/ --assert=plain
```

Because I don't want to install every dev dependency, I first `poetry install --no-dev`, then manually install needed dev dependencies, including `pytest, pytest-xdist, pyhamcrest`.

The result is, every time test is run, Poetry would remove all dev dependencies first because of the default behavior. This made tests very slow. If there's a way to turn it off, those packages can be cached and tests can run a lot faster.

![image](https://user-images.githubusercontent.com/2592205/88363989-81554a80-cd36-11ea-81f2-1d579ea611a3.png)

**Comment by jdahm** [comment] 2020-08-01 17:34
@laike9m I have this same problem and worked around it for now by exporting the set of non-dev dependencies to a `requirements.txt` file format, and installing those with pip. My project's `noxfile.py` now start with:

```python
import tempfile
from contextlib import contextmanager

import nox

@contextmanager
def requirements_from_poetry(session, dev=False):
    """Return a requirements.txt file with dependencies from Poetry."""
    with tempfile.NamedTemporaryFile() as tmpfile:
        args = [
            "poetry",
            "export",
            "--format=requirements.txt",
            f"--output={tmpfile.name}",
        ]
        if dev:
            args += ["--dev"]

        session.run(*args, external=True)
        yield tmpfile.name


def install_with_constraints(session, *args, **kwargs):
    """Install packages constrained by Poetry's lock file."""
    with requirements_from_poetry(session, dev=True) as requirements:
        session.install(f"--constraint={requirements}", *args, **kwargs)


@nox.session(python="3.8")
def tests(session):
    """Run the test suite."""
    args = session.posargs or ["--cov", "-m", "not e2e"]
    install_with_constraints(
        session, "coverage[toml]", "pytest", "pytest-cov",
    )
    with requirements_from_poetry(session) as requirements:
        session.install("-r", requirements)
    session.install(".")
    session.run("pytest", *args)
```

**Comment by laike9m** [comment] 2020-08-01 17:41
@jdahm Thanks for showing the workaround. I still have faith in Poetry that this will eventually be supported. @sdispater any thoughts?

**Comment by owais** [comment] 2021-03-19 00:34
This is quite a big pain point actually. It'd be nice to at least have a flag to turn this behavior off. Here is how I'm trying using it. 

I'm working on a library say LibA and I need to manually test it in multiple apps during development. From docs and `poetry install --help`, it seems `poetry install --no-dev` is the exactly what I need because of: 

```
  --no-dev               Do not install the development dependencies.
```

Intuitively, I felt I'd do the following:

```
# currently in my poetry managed LibA project
> pwd
~/LibA

# activate my test app's venv
. ~/app/venv/bin/activate

# install LibA as an editable package in app's env
poetry install --no-dev
```

This installs LibA as an editable install in app's venv. Now I should be able to run the app, make changes to LibA and have them reflect in the app without having to re-install LibA after every change. 

However, this doesn't work exactly as expected. When `poetry install` is executed with the `--no-dev` option, it looks up for all dev dependencies of LibA and uninstalls them from app's env. This is a huge issue if app has any packages in common with LibA's dev dependencies. What makes it even worse is that poetry removes even indirect dependencies which makes it very likely for the deps to match.


I feel the default behavior should be to not install dev dependencies when `--no-dev` is passed (as it is documented) and to not remove any packages at all. If that is not desirable for some reason, we should be able to pass in another CLI param that prevents poetry from removing packages. Something like `poetry install --no-dev --no-remove`. 

BTW what use cases demand that dev packages get removed when `--no-dev` is passed? Poetry already spports a `--remove-untracked` option. May be if a user wants to remove dev deps, they can run `poetry install --no-dev --remove-untracked` and this would ensure any dev deps are uninstalled. `poetry install --no-dev` would only install packages and never remove anything.

Question: Is there another ideal way to work with the workflow that I described above when using poetry?

**Comment by untereiner** [comment] 2021-07-19 14:06
@sdispater Any idea on how to install --no-dev without this remove first ?
