### ISSUE TITLE
Expose Locker.is_fresh as a command

### ISSUE THREAD

**Issue by phobologic** [sdispater/poetry#773] opened 2019-01-03 22:33 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'd like to be able to ensure, in our CI system, that whenever someone commits a new pyproject.toml that they've also updated poetry.lock to match.  I saw that someone had done the opposite because of a warning from `installation.installer.Installer._do_install` calling to `packages.locker.Locker.is_fresh()`, and I'd love to have that functionality exposed so that I could prevent this in the future.

Happy to help with a PR, but not sure if this should be a new command or a flag on an older command.  Thanks!

**Comment by sdispater** [comment] 2019-11-01 17:44
Duplicate of #1406. Closing this one to track the discussion in one place.

**Closed by sdispater** 2019-11-01 17:44 UTC
