### ISSUE TITLE
pip install url to the wheel whl

### ISSUE THREAD

**Issue by ZhukovGreen** [sdispater/poetry#880] opened 2019-02-11 05:39 UTC
- [ X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
I am looking for a way to solve this `pip install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl` with poetry. I need to install a whl package which lives in the web. I found it is possible for wheels, which are available locally but can't find any clue for remote wheels

**Comment by romaia** [comment] 2019-02-21 17:08
You mean you want to add a dependency of a package that lives in an url, instead of a localfile?

Maybe this is a duplicate of bug #695

**Comment by ZhukovGreen** [comment] 2019-02-23 13:09
Thx, this is really a duplicate

**Closed** 2019-08-02 15:16 UTC
