### ISSUE TITLE
Poetry uses incorrect Python

### ISSUE THREAD

**Issue by pikeas** [sdispater/poetry#1470] opened 2019-10-17 01:15 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15
- **Poetry version**: 1.0.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pikeas/5c45fc9fd32353b5aee37163f95ef14d

## Issue

Possibly related: https://github.com/sdispater/poetry/issues/439#issuecomment-423574924, https://github.com/sdispater/poetry/issues/536, https://github.com/sdispater/poetry/issues/988, https://github.com/sdispater/poetry/issues/1386.

```
$ python -V
3.7.4
$ poetry install -vvv

[RuntimeError]
The current Python version (3.8.0) is not supported by the project (~3.7)
Please activate a compatible Python version.

Traceback (most recent call last):
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/clikit/console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/clikit/api/command/command.py", line 165, in _do_handle
    self._dispatcher.dispatch(ConsoleEvents.PRE_HANDLE.value, event)
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/pikeas/.local/pipx/venvs/poetry==1.0.0.b2/lib/python3.8/site-packages/poetry/console/config/application_config.py", line 84, in set_env
    raise RuntimeError(
```

Poetry is installed under Python 3.8, the currently activated Python is 3.7, and pyproject.toml has Python pinned to `~3.7` (rather than the more common `^3.7`).

I expected Poetry to use the active version of Python, instead it uses the version of Python it was installed under, which fails.

**Comment by sdispater** [comment] 2019-10-17 11:10
Duplicate of #536 which is currently being fixed.

**Closed by sdispater** 2019-10-17 11:10 UTC
Labels: Bug
