### ISSUE TITLE
[TooManyRedirects] Exceeded 30 redirects.

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#1033] opened 2019-04-12 11:53 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

n poetry update in my project i get 

    [TooManyRedirects]
    Exceeded 30 redirects.

I have attached the log for `poetry update -vvv` and hope that somebody can help me figure out the root of this problem.

[poetry log.txt](https://github.com/sdispater/poetry/files/3073110/poetry.log.txt)

**Comment by le717** [comment] 2019-04-13 02:31
I am also getting this error when trying to run `poetry add mailjet_rest`. I was trying to start a new install of my project and this is the only library I cannot install, which means I can't fully install my project because of this error. I've attached the output of `poetry add mailjet_rest -vvv`, in case it helps any.

[poetry-log.txt](https://github.com/sdispater/poetry/files/3075651/poetry-log.txt)

**Comment by drunkwcodes** [comment] 2019-04-13 13:05
@le717 May you retry? I ran it with the same command and it's fine.

**Comment by le717** [comment] 2019-04-13 13:11
@drunkwcodes I just tried it again with a clean venv, created by poetry, and got the same error and debug output. I'm using Win 10 x64 and Py 3.6/3.7 x86. The weird thing is this used to work, as my original venv successfully added it.

**Comment by josh-stableprice** [comment] 2019-04-24 14:02
Have you tried the "fix" from #728 of clearing the cache. Just worked for me, and is something that needs to be fixed.

**Comment by kakulukia** [comment] 2019-04-24 14:34
Awesome, that fixed my problem! 
That hint might be displayed along with the too many redirects error?

**Comment by kakulukia** [comment] 2019-04-24 14:59
thx @josh-stableprice !

**Comment by le717** [comment] 2019-04-27 02:21
@josh-stableprice I just got a chance to try that and it seems to have fixed the issue. Thank you! Although hopefully the root issue can be found and fixed, it's good to know there is a (strange but working) workaround.

**Comment by stephsamson** [comment] 2019-06-26 19:40
Thanks for submitting this issue! Since this is a duplicate of the open issue #728, I will close this for now in order to keep the discussions regarding `[TooManyRedirects]` in one place.

**Closed by stephsamson** 2019-06-26 19:40 UTC

**Comment by bohblue2** [comment] 2022-06-10 13:27
Thanks, Pypi is not working until now.

**Comment by severo** [comment] 2022-06-10 13:27
https://stackoverflow.com/questions/72551057/poetry-gives-toomanyindirects-error-suddenly

**Comment by ahmadhori** [comment] 2022-06-10 13:44
luckily I could borrow the virtual environment of my team mate so I don't need to wait for this issue to get fixed :D

**Comment by andrea-mucci** [comment] 2022-06-10 18:52
the Pypi seems recovered by still have the same problem

` 
TooManyRedirects

  Exceeded 30 redirects.

  at ~/.poetry/lib/poetry/_vendor/py3.9/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│ 
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│ 
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│ 

`

i have cleared the cache but nothing changed....
