### ISSUE TITLE
cache:clear may delete entire directories

### ISSUE THREAD

**Issue by lcorreia** [sdispater/poetry#408] opened 2018-08-28 17:57 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: any Linux
- **Poetry version**: 0.11.4

If you run `poetry cache:clear --all /home/dev` (not a cache directory), all files in that directory are deleted. That should not happen. I expect the command cache:clear to clear only cache files.

Regards

**Comment by sdispater** [comment] 2018-08-28 20:46
Sorry about that! This is obviously the wrong behavior, and a dangerous one too.

I think I know where the problem is coming from.

I will keep you posted.

**Comment by sdispater** [comment] 2018-09-05 15:00
This is fixed in the latest `0.11.5` release :-)

**Closed by sdispater** 2018-09-05 15:00 UTC
Labels: CLI, bug
