### ISSUE TITLE
Support remote 'path' dependencies (e.g. https tar.gz)

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [sdispater/poetry#1231] opened 2019-07-16 17:10 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
In both `pip` and (a horrible comparison I know) `pipenv` it's possible to install a file dependency with a remote host, but all the ways I've tried to do this with `poetry` seem to error out and I can't see any mention of support in the docs.

This is useful for the [recommended production model dependency workflow](https://spacy.io/usage/models#production) (or just the [standard pip workflow](https://spacy.io/usage/models#download-pip)) for the `spaCy` library: a natural language processing tool with published model packages that are too big to distribute via standard PyPI.

My target behaviour would be for `poetry` to recognise if a provided `path` is a qualified URL and resolve it if so - as similarly to how `pip` would as is practical (e.g. I don't even know if `pip` supports authentication or other non-http(s) protocols). Sorry I'm not (yet) familiar with the poetry codebase, but I hope it would be a relatively minor change since `pip` seems to provide native support?

If this feature would be complex but there's an obvious workaround it'd be really helpful for me too!

**Comment by iwoloschin** [comment] 2019-07-17 11:12
I believe this is a duplicate of #1200?

**Comment by sdispater** [comment] 2019-08-02 13:46
This has been added in #1260. It will be available in the `1.0.0` release.

**Closed by sdispater** 2019-08-02 13:46 UTC
