### ISSUE TITLE
Key "hashes" does not exist.

### ISSUE THREAD

**Issue by mbelang** [sdispater/poetry#1523] opened 2019-10-31 12:24 UTC
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10
- **Poetry version**: 1.0.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
It seems that poetry 1.0.0b3 is removing the `[metadata.hashes]`. So it makes is incompatible with older version of poetry i.e. 1.0.0b2 or 0.12.x for instance. Is that a bug or it was intentional?

here is the stack trace:

```
Step 10/12 : RUN poetry -vvv install --no-dev
 ---> Running in f2153be1029f
Creating virtualenv hello-k8s-py3.7 in /root/.cache/pypoetry/virtualenvs
Using virtualenv: /root/.cache/pypoetry/virtualenvs/hello-k8s-py3.7
Installing dependencies from lock file
                                  
[NonExistentKey]   
'Key "hashes" does not exist.'  
                                  
Exception trace:
 /usr/local/lib/python3.7/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /usr/local/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /usr/local/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /usr/local/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /usr/local/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /usr/local/lib/python3.7/site-packages/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /usr/local/lib/python3.7/site-packages/poetry/console/commands/install.py in handle() at line 55
   return_code = installer.run()
 /usr/local/lib/python3.7/site-packages/poetry/installation/installer.py in run() at line 73
   self._do_install(local_repo)
 /usr/local/lib/python3.7/site-packages/poetry/installation/installer.py in _do_install() at line 169
   locked_repository = self._locker.locked_repository(True)
 /usr/local/lib/python3.7/site-packages/poetry/packages/locker.py in locked_repository() at line 86
   package.hashes = lock_data["metadata"]["hashes"][info["name"]]
 /usr/local/lib/python3.7/site-packages/tomlkit/items.py in __getitem__() at line 1008
   return self._value[key]
 /usr/local/lib/python3.7/site-packages/tomlkit/container.py in __getitem__() at line 524
   raise NonExistentKey(key)

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

**Comment by pikacic** [comment] 2019-11-03 01:53
This is a duplicate of #1510

**Comment by stephsamson** [comment] 2019-11-08 15:07
Closing because #1510 exists.

**Closed** 2019-11-08 15:07 UTC
Labels: Bug
